# Generated by Django 5.0.2 on 2024-03-21 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_attendancerecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
    ]
