# Generated by Django 5.0.2 on 2024-03-21 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_student_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancerecord',
            old_name='hours_worked',
            new_name='minutes_worked',
        ),
    ]
