# Generated by Django 5.0.6 on 2024-11-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_hours_worked_attendancerecord_minutes_worked'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email_id',
            field=models.EmailField(default='', max_length=100),
        ),
    ]
